{
 "title": "Kafka Metrics_VF",
 "description": "Dashboard for metrics jmx_exporter protmetheus",
 "tags": [
  "stable",
  "kafka"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate, job)"
    }
   },
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount{job=\"$job\"}, topic)"
    }
   },
   {
    "name": "online_broker",
    "query": {
     "query": "query_result(count(up{job=~\"$job\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replica_manager_leadercount{job=\"kafka\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_activecontrollercount{})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_globaltopiccount{})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replica_manager_underreplicatedpartitions{})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replica_manager_partitioncount{})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_offlinepartitionscount{})"
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_activecontrollercount{}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(kafka_server_broker_topic_metrics_messagesinpersec_rate{}[1m]))",
     "legendFormat": "Total messages in per sec "
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 5 },
   "targets": [
    {
     "expr": "(kafka_server_replica_manager_leadercount{instance=\"jmx-kafka101:5556\", job=\"kafka\"} / kafka_server_replica_manager_partitioncount\n{instance=\"jmx-kafka101:5556\", job=\"kafka\"}) * 100"
    },
    {
     "expr": "kafka_server_replica_manager_leadercount{instance=\"jmx-kafka101:5556\", job=\"kafka\"}"
    },
    {
     "expr": "count(kafka_cluster_partition_replicascount{instance=\"jmx-kafka101:5556\", job=\"kafka\"} <= 1)by(instance)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_server_broker_topic_metrics_messagesinpersec_rate{}[$__range]))",
     "legendFormat": "Total messages from ${__from:date:MM-DD hA} to ${__to:date:MM-DD hA}"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (kafka_network_socket_server_processor_avg_idle_percent{}*100)",
     "legendFormat": "Network processor avg {{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "type": "gauge",
     "description": "If <= 0 is very idle",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
     "repeat": "broker",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - rate(kafka_server_request_handler_avg_idle_percent{job=\"kafka\",instance= \"jmx-kafka101:5556\"}[1m]) / 10000000",
       "legendFormat": "Request handler avg {{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_request_metrics_time_ms{request=\"Produce\",job=\"kafka\",aggregate=\"99thPercentile\",instance=\"jmx-kafka101:5556\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_request_metrics_time_ms{request=\"FetchConsumer\",job=\"kafka\",aggregate=\"99thPercentile\",instance=\"jmx-kafka101:5556\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kafka_network_request_metrics_time_ms{request=\"FetchFollower\",job=\"kafka\",aggregate=\"99thPercentile\",instance=\"jmx-kafka101:5556\"})by(request)",
     "legendFormat": "Total {{request}} 99th"
    }
   ]
  },
  {
   "title": "Produce Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_request_metrics_time_ms{request=\"Produce\",job=\"kafka\",aggregate=\"99thPercentile\",instance=\"jmx-kafka101:5556\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_request_metrics_time_ms{request=\"FetchConsumer\",job=\"kafka\",aggregate=\"99thPercentile\",instance=\"jmx-kafka101:5556\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FetchFollow Latency 99th per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(kafka_network_request_metrics_time_ms{request=\"FetchFollower\",job=\"kafka\",aggregate=\"99thPercentile\",instance=\"jmx-kafka101:5556\"})by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "reqps", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "\nsort(sum(rate(kafka_server_broker_topic_metrics_messagesinpersec_rate{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\",topic!=\"\"}[1m]))by(topic))\n#sort(sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",instance=~\"jmx-kafka101:5556\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic))\n",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_broker_topic_metrics_bytesinpersec_rate{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\", topic!=\"\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_broker_topic_metrics_bytesoutpersec_rate{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\", topic!=\"\"}[1m]))by(instance)\n\n#sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum(rate(kafka_server_broker_topic_metrics_bytesinpersec_rate{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\", topic!=\"\"}[1m]))by(instance)\n#sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_broker_topic_metrics_bytesoutpersec_rate{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\", topic!=\"\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Total Produce Request Rate Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_totalproducerequests_total{job=\"$job\",instance=~\"$broker\",topic!=\"\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"Produce\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  { "title": "Troubleshooting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Failed Produce Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Produce Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedproducerequests_total{job=~\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Failed Fetch Request Per Topic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kafka_server_brokertopicmetrics_failedfetchrequests_total{job=~\"$job\",topic!=\"\",instance=~\"$broker\",topic=~\"$topic\"}[1m]))by(topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Disconnects Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 85 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "\nsum(rate(kafka_zookeeper_session_expire_listener_zookeeperdisconnectspersec{aggregate=\"OneMinute\",env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"}[1m]))by(instance)\n#sum(rate(kafka_server_sessionexpirelistener_zookeeperdisconnects_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Expires Per Sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 85 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_zookeeper_session_expire_listener_zookeeperexpirespersec{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"})by(instance)\n#sum (irate(kafka_server_sessionexpirelistener_zookeeperexpires_total{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Request Latency Ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 85 },
   "yaxes": [
    { "format": "ms", "label": "Time/ms" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_zookeeperclientmetrics_zookeeperrequestlatencyms{job=\"$job\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks / Isr Expands Per Sec",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
   ],
   "targets": [
    {
     "expr": "\nkafka_server_replica_manager_isrshrinkspersec{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"}\n#sum (irate(kafka_server_replicamanager_isrshrinks_total{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Shrinks Per Sec"
    },
    {
     "expr": "kafka_server_replica_manager_isrexpandspersec{aggregate=\"OneMinute\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"}\n#sum (irate(kafka_server_replicamanager_isrexpands_total{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "ISR Expands Per Sec"
    }
   ]
  },
  {
   "title": "FetchFollower Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 93 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_network_requestmetrics_requests_total{request=~\"FetchFollower\",job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "FetchConsumer Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "reqps", "label": "Request/s" }
   ],
   "targets": [
    {
     "expr": "kafka_network_request_per_sec{aggregate=\"Mean\", env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", request=\"FetchConsumer\", service=\"kafka-broker\", version=\"3\"}\n#sum(irate(kafka_network_requestmetrics_requests_total{request=\"FetchConsumer\",job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Request: {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Fetch Purgatory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Fetch\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Total Fetch Request Per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "reqps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_server_brokertopicmetrics_totalfetchrequests_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
     "legendFormat": "Broker: {{instance}}"
    }
   ]
  },
  {
   "title": "Log Flush Stats Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_log_logflushstats_logflushrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[5m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Number of Requests Waiting in the Producer Purgatory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_delayedoperationpurgatory_purgatorysize{job=\"$job\",delayedOperation=\"Produce\",instance=~\"$broker\"})by(instance)",
     "legendFormat": "Broker {{instance}}"
    }
   ]
  },
  {
   "title": "Leader Election Rate Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 119 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (irate(kafka_controller_controllerstats_leaderelectionrateandtimems_count{job=\"$job\",instance=~\"$broker\"}[1m]))by(instance)",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Leader Per Broker",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", partition=\"0\", service=\"kafka-broker\", topic!=\"\"}\n#kafka_cluster_partition_replicascount{job=~\"$job\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Disk Usage Segment Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_log_size{env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", partition=\"0\", service=\"kafka-broker\", topic!=\"\"})by(instance))\n#sort(sum(kafka_log_log_size{job=~\"$job\",instance=~\"$broker\"})by(instance))",
     "legendFormat": "Instance Broker:  {{instance}}"
    }
   ]
  },
  {
   "title": "Count Partition per Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 145 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sort(sum(kafka_server_replica_manager_partitioncount{env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"}) by (instance))",
     "legendFormat": "Instance Broker: {{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "JVM Threads Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_jvm_thread_count{env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(kafka_jvm_os_committedvirtualmemorysize{env=\"cluster-demo\", instance=\"jmx-kafka101:5556\", job=\"kafka\", service=\"kafka-broker\"})\n#sum without(area)(jvm_memory_bytes_used{job=\"$job\",instance=~\"$broker\"} )",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 163 },
   "yaxes": [
    { "format": "s", "label": "Usage/s" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_jvm_os_processcputime{job=\"kafka\"}[1m])",
     "legendFormat": "Broker - {{instance}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 163 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$job\",instance=~\"$broker\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}